console.log("■ prac02.ts の実行");
import "./prac02";
console.log("■ prac03.ts の実行");
import "./prac03";
console.log("■ comp.ts の実行");
import "./comp";
console.log("■ prac04.ts の実行");
import "./prac04";
console.log("■ prac05.ts の実行");
import "./prac05";